module Joybox
  module Core

    module KeyboardEvent

      # Keyboard Events
      key_states = [:down, :up, :flag_changed]

      key_states.each do |key_state|
        define_method("on_key_#{key_state}") do |&block|
          self.keyboardEnabled = true if block_given?
          instance_variable_set("@on_key_#{key_state}_block", block)
        end
      end

      # These methods can't be autogenerated using metaprogramming
      # because Objective-C will call them
      def ccKeyDown(event)
        @on_key_down_block.call(event) if @on_key_down_block
        @on_key_down_block ? true : false
      end

      def ccKeyUp(event)
        @on_key_up_block.call(event) if @on_key_up_block
        @on_key_up_block ? true : false
      end

      def ccFlagsChanged(event)
        @on_key_flag_changed_block.call(event) if @on_key_flag_changed_block
        @on_key_flag_changed_block ? true : false
      end

    end

  end
end
